// AUTO-GENERATED by scripts/version_bump.py — do not edit by hand.
// Manual fields: version.txt (MAJOR.MINOR), build_number.txt (BUILD).
export const VERSION = "1.1.0";
export const BUILD_DATE = "2026-07-03 17:22:21";
